version: "2.2"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_DEBUG: "true"
    networks:
      - app-network
  webserver:
    depends_on:
      - web
    image: nginx:alpine
    volumes:
      - ./src:/usr/app/
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: webserver
    restart: unless-stopped
    ports:
      - "4000:80"
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge